# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path

from PyInstaller.utils.hooks import collect_submodules

block_cipher = None

_here = Path(SPECPATH)
_core_root = (_here / ".." / "packages" / "vectortrack-core").resolve()

_vectortrack_hiddenimports = [
    'vectortrack',
    'vectortrack.app',
    'vectortrack.process_monitor',
    'vectortrack.activity_monitor',
    'vectortrack.config',
    'vectortrack.log_parser',
    'vectortrack.sync_config',
    'vectortrack.sync_folder',
    'vectortrack.settings_store',
    'vectortrack.session_logger',
    'vectortrack.licensing',
    'vectortrack.single_instance',
    'vectortrack.budget',
    'vectortrack.db',
    'vectortrack.db.repository',
    'vectortrack.db.schema',
    'vectortrack.db.session_repository',
    'vectortrack.db.rate_resolver',
    'vectortrack.models',
    'vectortrack.models.session',
    'vectortrack.models.billable_project',
    'vectortrack.models.rows',
    'vectortrack.ui',
    'vectortrack.ui.main_window',
    'vectortrack.ui.theme',
    'vectortrack.ui.dashboard_strip',
    'vectortrack.ui.open_files_table',
    'vectortrack.ui.project_summary_table',
    'vectortrack.ui.history_browser',
    'vectortrack.ui.heatmap_widget',
    'vectortrack.ui.clients_tab',
    'vectortrack.ui.tray',
    'vectortrack.ui.app_icon',
    'vectortrack.ui.hud_window',
    'vectortrack.ui.formatting',
    'vectortrack.ui.layout_utils',
    'vectortrack.ui.dialogs',
    'vectortrack.ui.dialogs.about_dialog',
    'vectortrack.ui.dialogs.donate_dialog',
    'vectortrack.ui.dialogs.settings_dialog',
    'vectortrack.ui.dialogs.project_editor_dialog',
    'vectortrack.ui.dialogs.new_project_dialog',
    'vectortrack.ui.dialogs.project_assign_dialog',
    'vectortrack.ui.dialogs.manual_entry_dialog',
    'vectortrack.ui.dialogs.session_edit_dialog',
    'vectortrack.ui.dialogs.session_explorer_dialog',
    'vectortrack.ui.dialogs.first_run_wizard',
    'vectortrack.ui.dialogs.client_editor_dialog',
    'vectortrack.ui.dialogs.log_library_dialog',
    'vectortrack.ui.dialogs.import_bundle_dialog',
    'vectortrack.ui.dialogs.backup_restore_dialog',
    'vectortrack.ui.dialogs.report_dialog',
    'vectortrack.ui.dialogs.bug_report_dialog',
    'vectortrack.ui.dialogs.update_check_dialog',
    'vectortrack.ui.dialogs.catalog_sync_dialog',
    'vectortrack.ui.dialogs.rate_edit_dialog',
    'vectortrack.ui.dialogs.vectorworks_setup_dialog',
    'vectortrack.ui.dialogs.vectorworks_log_setup_dialog',
    'vectortrack.services',
    'vectortrack.services.hotkey_service',
    'vectortrack.services.notification_service',
    'vectortrack.services.autostart',
    'vectortrack.services.update_service',
    'vectortrack.services.alias_resolver',
    'vectortrack.services.backup_service',
    'vectortrack.services.billing_service',
    'vectortrack.services.import_export',
    'vectortrack.services.log_service',
    'vectortrack.services.report_data',
    'vectortrack.services.report_service',
    'vectortrack.services.tracking_service',
    'vectortrack.services.tracking_persistence',
    'vectortrack.services.session_aggregator',
    'vectortrack.services.vw_identity',
    'vectortrack.services.sync_coordinator',
    'vectortrack.services.catalog_sync',
    'vectortrack.services.catalog_serializer',
    'vectortrack.services.catalog_diff',
    'vectortrack.services.catalog_applier',
    'vectortrack.services.project_sync',
    'PyQt6.QtCore',
    'PyQt6.QtGui',
    'PyQt6.QtNetwork',
    'PyQt6.QtWidgets',
    'reportlab',
    'reportlab.lib',
    'reportlab.platypus',
    'reportlab.pdfbase',
    'reportlab.pdfgen',
    'psutil',
    'pynput',
    'pynput.keyboard',
    'pynput.mouse',
    'cryptography',
    'loguru',
    'win32gui',
    'win32process',
    'win32con',
    'win32api',
]

a = Analysis(
    ['run.py'],
    pathex=[str(_here), str(_core_root)],
    binaries=[],
    datas=[('assets', 'assets')],
    hiddenimports=_vectortrack_hiddenimports + collect_submodules('vectortrack_core'),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='VectorTrack',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon='assets/vectortrack.ico',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='VectorTrack',
)
